# Assignment

what is broadcasting ? explain with an example apply functions like reshape ,resize, ndim on the output of broadcasting?


In [1]:
import numpy as np
#ans:
# Definition:
# Broadcasting means NumPy automatically expands arrays of different shapes
# so mathematical operations can be performed without manually repeating data.
#example:
a = np.array([[1],[2],[3]])      # shape (3,1)
b = np.array([10,20,30])        # shape (3,)

c = a + b

print("Broadcasting Output:")
print(c)

Broadcasting Output:
[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [2]:
print("Shape:", c.shape)
print("ndim:", c.ndim)

# reshape
print(c.reshape(1,9))

# resize
c.resize((9,1))
print(c)

Shape: (3, 3)
ndim: 2
[[11 21 31 12 22 32 13 23 33]]
[[11]
 [21]
 [31]
 [12]
 [22]
 [32]
 [13]
 [23]
 [33]]


create an array apply all the aggregation functions like mean,median,mode,variance,std, dot product ?


In [3]:
from scipy import stats

arr = np.array([10,20,30,40,50])

print("Mean:", np.mean(arr))
print("Median:", np.median(arr))
print("Mode:", stats.mode(arr))
print("Variance:", np.var(arr))
print("Standard Deviation:", np.std(arr))

# Dot Product
x = np.array([1,2,3])
y = np.array([4,5,6])

print("Dot Product:", np.dot(x,y))   # 1*4 +2*5 +3*6 = 32


Mean: 30.0
Median: 30.0
Mode: ModeResult(mode=np.int64(10), count=np.int64(1))
Variance: 200.0
Standard Deviation: 14.142135623730951
Dot Product: 32


explain the difference between flatten and ravel with an example ?

In [4]:
mat = np.array([[1,2],[3,4]])

f = mat.flatten()
r = mat.ravel()

print("Flatten:", f)
print("Ravel:", r)

# Difference:
# flatten() returns copy
# ravel() returns view (linked to original)

r[0] = 100
print(mat)   # original changes

Flatten: [1 2 3 4]
Ravel: [1 2 3 4]
[[100   2]
 [  3   4]]


create an array using random function ?


In [5]:
print(np.random.rand(2,3))       # 0 to 1
print(np.random.randint(1,10,(2,2)))


[[0.45765097 0.81649798 0.41168805]
 [0.29502361 0.19354796 0.33862659]]
[[5 1]
 [8 7]]


what is random.seed() and how does it work?


In [6]:
np.random.seed(10)
print(np.random.randint(1,100,5))

np.random.seed(10)
print(np.random.randint(1,100,5))

[10 16 65 29 90]
[10 16 65 29 90]


explain the diff between skewness,kurtosis?

In [7]:
data = [2,3,4,5,6,7,100]

print("Skewness:", stats.skew(data))
print("Kurtosis:", stats.kurtosis(data))

# Skewness:
# Measures asymmetry of data

# >0 = right skewed
# <0 = left skewed
# =0 = symmetric

# Kurtosis:
# Measures peakness / tail heaviness

# High kurtosis = more outliers
# Low kurtosis = flatter distribution

Skewness: 2.0316737294684932
Kurtosis: 2.1458505234924923


what is correlation ?

In [8]:
x = [1,2,3,4,5]
y = [2,4,6,8,10]
print("Correlation:", np.corrcoef(x,y))
# Correlation tells relationship between two variables# +1  perfect positive# -1  perfect negative# 0   no relation

Correlation: [[1. 1.]
 [1. 1.]]
